config/routes.rb
Rails.application.routes.draw do

  resources :courses

  resources :courseplans do
    resources :plan_entries, only: [:new, :create, :destroy, :update]
  end

  get 'users/new'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#index'
  match '/register', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/change_active_courseplan', to: 'users#change_active_courseplan', via: 'patch'

end

app/models/plan_entry.rb
class PlanEntry < ActiveRecord::Base
  include Semesterable
  belongs_to :courseplan
  belongs_to :course
  
  validates_uniqueness_of :course_id, scope: :courseplan_id
  
  # SEASONS is defined in initalizers because it's shared across models
  # (at least as of the writing of this comment.)
  
  def set_semester(options = {})
    year = options[:year]
    season = options[:season]
    if (!year.is_a? Integer) || (!GlobalConstants::SEASONS.has_key? season)
      self.update(semester: nil)
    else
      self.update(semester: DateTime.new(year, GlobalConstants::SEASONS[season].first))
    end
  end
  
  def no_semester!
    self.update(semester: nil)
  end
  
  def semester_to_string
      convert_semester_datetime_to_string(self.semester)
  end
  
end

app/controllers/plan_entries_controller.rb
class PlanEntriesController < ApplicationController
  
  def create
    @courseplan = current_user.courseplans.find_by(id: params[:courseplan_id])
    @course = Course.find_by(id: params[:course])
    @courseplan.add_course!(@course)
    redirect_to :back
  end
  
  def destroy
    @courseplan = current_user.courseplans.find_by(id: params[:courseplan_id])
    @plan_entry = @courseplan.plan_entries.find_by(id: params[:id])
    @course = Course.find_by(id: @plan_entry.course_id)
    @courseplan.remove_course!(@course)
    redirect_to :back
  end
  
  def update
    @courseplan = current_user.courseplans.find_by(id: params[:courseplan_id])
    @plan_entry = @courseplan.plan_entries.find_by(id: params[:id])
   if params[:no_semester]
     @plan_entry.no_semester!
   else
     season,year = params[:Choose][:semester].split(' ')
     @plan_entry.set_semester(year: year.to_i, season: season.downcase.to_sym)
  end
  
  redirect_to :back
  end
end

app/helpers/plan_entries_helper.rb
module PlanEntriesHelper
  
  def format_semester(semester_key)
    formatted_string = semester_key.to_s.gsub!('_', ' ')
    formatted_string[0] = formatted_string[0].upcase
    formatted_string
  end
  
  def default_semester_for(entry)
    semester = entry.semester_to_string || entry.upcoming_semester
  end
  
end

app/views/plan_entries/_semester_change_form.html.erb
<div class="semester-widget">
  <%= form_tag(courseplan_plan_entry_path(courseplan.id, entry.id), method: :patch) do %>
    Change semester:
    <%= select("Choose", "semester",
               semester_with_year_hash(GlobalConstants::SEASONS),
               {selected: default_semester_for(entry)},
               {:onchange => "this.form.submit()"}) %>
    <% if !entry.semester.nil? %>
      <%= link_to 'No semester',
                  courseplan_plan_entry_path(courseplan.id, entry.id, :no_semester => true),
                  method: :patch,
                  class: "btn btn-xs btn-default"%>
    <% else %>
    <%= submit_tag("Update", class: "btn btn-xs btn-default") %>
    <% end %>  
  <% end %>
    

    
  
</div>

app/views/plan_entries/show.html.erb
<%= @no_semester %>