config/routes.rb
Rails.application.routes.draw do

  resources :courses

  resources :courseplans do
    resources :plan_entries, only: [:new, :create, :destroy, :update]
  end

  get 'users/new'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#index'
  match '/register', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/change_active_courseplan', to: 'users#change_active_courseplan', via: 'patch'

end

app/models/courseplan.rb
class Courseplan < ActiveRecord::Base
  include Semesterable
  include Creditable
  
  belongs_to :user
  has_many :plan_entries, dependent: :destroy
  has_many :courses, through: :plan_entries
  validates :user, presence: true
  validates :name, presence: true
  validates :name, :uniqueness => {:scope => [:user_id] }
  
  def add_course!(course)
    self.plan_entries.create(course_id: course.id)
  end
  
  def remove_course!(course)
    self.plan_entries.find_by(course_id: course.id).destroy
  end
  
  def has_course?(course)
    self.plan_entries.find_by(course_id: course.id)
  end
  
  def courses_by_semester
    semesters = ActiveSupport::OrderedHash.new{ |hash, key| hash[key] = Array.new }
    self.plan_entries.order('semester ASC').each do |entry|
      sem = entry.semester
      if sem.nil?
        semesters[:no_semester] << entry
      else
        season = get_season_from(sem)
        year = get_year_from(sem)
        semester_key = "#{season}_#{year}".to_sym
        semesters[semester_key] << entry
      end
    end
    semesters
  end
  
  def total_credits
    calculate_credits_for self.courses.sum(:credits)
  end
  
  def has_too_many_courses?
    self.total_credits > GlobalConstants::MAX_CREDITS
  end
  
end

app/controllers/courseplans_controller.rb
class CourseplansController < ApplicationController
  before_action :correct_user, only: [:show, :destroy]

  def new
    @courseplan = Courseplan.new
  end

  def create
    @courseplan = current_user.courseplans.new(courseplan_params)

    if @courseplan.save
      flash[:success] = "New plan created!"
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def show
    plans = current_user.courseplans.all
    @courseplan = plans.find(params[:id])
  end

  def destroy
    @courseplan = current_user.courseplans.find_by(id: params[:id])
    @courseplan.destroy
    redirect_to root_url
  end
  

    private

      def courseplan_params
        params.require(:courseplan).permit(:name)
      end

      def correct_user
        current_user.courseplans.find(params[:id])
        rescue ActiveRecord::RecordNotFound
          render :file => "public/401.html", :status => :unauthorized
      end
end

app/helpers/courseplans_helper.rb
module CourseplansHelper
  
  def show_courseplan_links(options={})
    current_user.all_courseplans(options).each do |plan|
      plan
    end
  end
  
end

app/views/courseplans/_courseplan_changes.html.erb
<%= render partial: 'courseplans/set_as_active', 
           locals: { courseplan: courseplan } \
    unless current_courseplan? courseplan  %>
<%= render partial: 'courseplans/delete_courseplan',
           locals: { courseplan: courseplan } %>

app/views/courseplans/_credit_total.html.erb
<% if courseplan.has_too_many_courses? %>
  <% divclass = "too-many-courses" %>
  <% message = "You have too many courses in your courseplan. You can take a maximum of #{GlobalConstants::MAX_CREDITS} credits worth of courses." %>
<% else %>
    <% divclass = "safe-course-amount" %>
    <% message = "" %>
<% end %>
<div class=<%= divclass %>>You have <%= pluralize courseplan.total_credits, 'credit' %> out of
  <%= pluralize GlobalConstants::MAX_CREDITS, 'credit' %>. <p><%= message %></p></div>
    
    
    

app/views/courseplans/_delete_courseplan.html.erb
<%= link_to 'Delete this course plan', courseplan_path(courseplan.id), 
      method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-large btn-danger" %>

app/views/courseplans/_main.html.erb
<% if current_user.courseplans.any? %>
  <%= render partial: 'courseplans/show_plan',
                      object: current_user.active_courseplan,
                      as: 'courseplan' %>
<% else %>
  <p>You currently have no course plans.</p>
<% end %>

<%= link_to "Create course plan", new_courseplan_path, class: "btn btn-primary" %>

app/views/courseplans/_other_courseplans.html.erb
<% if current_user.has_multiple_courseplans %>
  <p>Your other courseplans</p>
  <ul>
    <% current_user.all_courseplans(except: courseplan).each do |plan| %>
        <li><%= link_to plan.name, plan %></li>
    <% end %>
  </ul>
<% end %>

app/views/courseplans/_semesters.html.erb
<ul>
  <!-- Get rid of the duplication - probably by creating a method that puts the nil semester entries at the top of the hash. -->
  <% ordered_courseplan[:no_semester].each do |entry| %>
    <li><%= render partial: 'courses/course_widget',
                   locals: { courseplan: courseplan,
                             course: Course.find(entry.course_id)}%>
         <%= render partial: 'plan_entries/semester_change_form',
                  locals: { entry: entry, courseplan: courseplan} %></li>
  <% end %>
</ul>

<% ordered_courseplan.each do |semester, entries| %>
  <% unless semester == :no_semester %>
    <%= format_semester semester %>
    <ul>
      <% entries.each do |entry| %>
        <li><%= render partial: 'courses/course_widget',
                       locals: { courseplan: courseplan,
                                 course: Course.find(entry.course_id)}%>
            <%= render partial: 'plan_entries/semester_change_form',
                      locals: { entry: entry, courseplan: courseplan} %></li>        
      <% end %>
    </ul>
  <% end %>
  
<% end %>

app/views/courseplans/_set_as_active.html.erb
<%= link_to 'Set as active courseplan', change_active_courseplan_path(courseplan_id: courseplan.id), 
      method: :patch, class: "btn btn-large btn-info" %>

app/views/courseplans/_show_plan.html.erb
<h2>Course Plan: <%= courseplan.name %></h2>
<%= render partial: 'courseplans/courseplan_changes',
           locals: { courseplan: courseplan } %>
<% if courseplan.plan_entries.any? %>
  <%= render partial: 'courseplans/semesters',
             locals: { ordered_courseplan: courseplan.courses_by_semester, courseplan: courseplan }%>
  <%= render partial: 'courseplans/credit_total',
             locals: { courseplan: courseplan } %>
<% else %>
  <p>There don't seem to be any courses in this plan.</p>
<% end %>
<%= render partial: 'courseplans/other_courseplans',
                     object: courseplan,
                     as: 'courseplan' %>

app/views/courseplans/new.html.erb
<% provide(:title, "Create new courseplan") %>
<h1><%= yield(:title) %></h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for @courseplan, url: { action: "create" }, html: { class: "form-horizontal"} do |f| %>
      <%= render 'shared/error_messages', object: @courseplan %>
      
      <%= f.label :name, class: "control-label" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.submit "Create", class: "btn btn-large btn-success btn-form" %>
    <% end %>
  </div>
</div>

app/views/courseplans/show.html.erb
<% provide(:title, @courseplan.name) %>
<%= render partial: 'courseplans/show_plan',
           object: @courseplan,
           as: 'courseplan' %>