config/routes.rb
Rails.application.routes.draw do

  resources :courses

  resources :courseplans do
    resources :plan_entries, only: [:new, :create, :destroy, :update]
  end

  get 'users/new'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#index'
  match '/register', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/change_active_courseplan', to: 'users#change_active_courseplan', via: 'patch'

end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to 'CourseChooser', root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav">
        <% if signed_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to("(Admin)",'#') if current_user.admin? %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><%= link_to 'Sign out', signout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to 'Sign in', signin_path %></li>
        </ul>
        <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= format_title(yield :title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' if (signed_in? || !current_page?(root_path)) %>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>